// Agent-Ops lane queue — generated by @yattalo/task-system
//
// Prevents concurrent runs on the same lane.
// A lane is a logical grouping (e.g., "frontend", "backend") to prevent conflicts.

const activeLanes = new Map<string, string>(); // laneId -> runId

export function acquireLane(laneId: string, runId: string): boolean {
  if (activeLanes.has(laneId)) {
    return false; // lane is busy
  }
  activeLanes.set(laneId, runId);
  return true;
}

export function releaseLane(laneId: string, runId: string): void {
  if (activeLanes.get(laneId) === runId) {
    activeLanes.delete(laneId);
  }
}

export function isLaneBusy(laneId: string): boolean {
  return activeLanes.has(laneId);
}

export function getActiveLanes(): Map<string, string> {
  return new Map(activeLanes);
}
