// ============================================================
// Convex HTTP Router — auto-generated by @yattalo/task-system
// ============================================================

import { httpRouter } from "convex/server";
import { taskSystemRoutes } from "./taskSystem/http";

const http = httpRouter();

taskSystemRoutes.forEach((route) => http.route(route));

export default http;
