// Agent-Ops cleanup — generated by @yattalo/task-system
//
// Garbage collects stale worktrees older than 24h.

import { listStaleWorktrees, removeWorktree } from "./git-isolation.js";
import type { AgentOpsConfig } from "./types.js";

export function cleanupStaleWorktrees(config: AgentOpsConfig, maxAgeMs?: number): number {
  const stale = listStaleWorktrees(config, maxAgeMs);

  let cleaned = 0;
  for (const runId of stale) {
    try {
      removeWorktree(config, runId);
      console.log(`[cleanup] Removed stale worktree: ${runId}`);
      cleaned++;
    } catch (err) {
      console.error(`[cleanup] Failed to remove ${runId}: ${(err as Error).message}`);
    }
  }

  return cleaned;
}
