// Agent-Ops config loader — generated by @yattalo/task-system
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import type { AgentOpsConfig } from "./types.js";

const DEFAULT_CONFIG: AgentOpsConfig = {
  convexUrl: process.env.CONVEX_URL ?? "",
  pollInterval: 30000,
  maxConcurrentRuns: 3,
  maxRunsPerDay: 100,
  defaultTimeoutMinutes: 30,
  protectedBranches: ["main","master"],
  agentCommands: {
    claude: "claude",
    gemini: "gemini",
    codex: "codex"
  },
  projectRoot: process.cwd(),
  worktreeBase: resolve(process.env.HOME ?? "~", ".agent-ops", "worktrees"),
};

export function loadConfig(): AgentOpsConfig {
  // Try to load from task-system.config.ts at project root
  const configPath = resolve(process.cwd(), "task-system.config.ts");
  if (existsSync(configPath)) {
    // Config is TypeScript — in production this would use tsx or similar
    // For now, use defaults + env overrides
  }

  return {
    ...DEFAULT_CONFIG,
    convexUrl: process.env.CONVEX_URL ?? DEFAULT_CONFIG.convexUrl,
    pollInterval: parseInt(process.env.AGENT_OPS_POLL_INTERVAL ?? String(DEFAULT_CONFIG.pollInterval), 10),
    maxConcurrentRuns: parseInt(process.env.AGENT_OPS_MAX_CONCURRENT ?? String(DEFAULT_CONFIG.maxConcurrentRuns), 10),
  };
}
