// Agent-Ops shared types — generated by @yattalo/task-system

export interface AgentOpsConfig {
  convexUrl: string;
  pollInterval: number;
  maxConcurrentRuns: number;
  maxRunsPerDay: number;
  defaultTimeoutMinutes: number;
  protectedBranches: string[];
  agentCommands: Record<string, string>;
  projectRoot: string;
  worktreeBase: string;
}

export interface JobSnapshot {
  jobId: string;
  name: string;
  agent: string;
  prompt: string;
  executionMode: string;
  createPR: boolean;
  prBaseBranch?: string;
  maxDurationMinutes?: number;
  laneId?: string;
}

export interface RunContext {
  runId: string;
  jobId: string;
  agent: string;
  prompt: string;
  executionMode: string;
  worktreePath: string;
  branchName: string;
  baseBranch: string;
  startedAt: number;
}

export interface LogEntry {
  timestamp: number;
  level: "info" | "warn" | "error" | "debug";
  message: string;
}
