// Agent-Ops log streamer — generated by @yattalo/task-system
//
// Batches log entries and uploads them to Convex periodically.

import { execSync } from "node:child_process";
import type { LogEntry } from "./types.js";

export class LogStreamer {
  private buffer: LogEntry[] = [];
  private intervalId: ReturnType<typeof setInterval> | null = null;
  private readonly maxBatchSize = 20;
  private readonly flushIntervalMs = 5000;

  constructor(
    private readonly runId: string,
    private readonly projectRoot: string,
  ) {}

  start(): void {
    this.intervalId = setInterval(() => this.flush(), this.flushIntervalMs);
  }

  stop(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    this.flush(); // Final flush
  }

  push(entry: LogEntry): void {
    this.buffer.push(entry);
    if (this.buffer.length >= this.maxBatchSize) {
      this.flush();
    }
  }

  private flush(): void {
    if (this.buffer.length === 0) return;

    const entries = this.buffer.splice(0, this.maxBatchSize);

    try {
      execSync(
        `npx convex run taskSystem/agentOps:appendRunLog '${JSON.stringify({
          runId: this.runId,
          entries,
        })}'`,
        { cwd: this.projectRoot, stdio: "pipe", timeout: 10000 },
      );
    } catch (err) {
      // Re-add failed entries for next attempt
      this.buffer.unshift(...entries);
      console.error(`[log-streamer] Failed to flush logs: ${(err as Error).message}`);
    }
  }
}
