// Agent-Ops PR creator — generated by @yattalo/task-system
//
// Creates GitHub PRs from agent run branches using gh CLI.

import { execSync } from "node:child_process";
import type { RunContext } from "./types.js";

export interface PRResult {
  url: string;
  number: number;
}

export function createPR(run: RunContext, summary?: string): PRResult | null {
  try {
    // Check if there are commits to push
    const commitCount = execSync(
      `git rev-list --count ${run.baseBranch}..HEAD`,
      { cwd: run.worktreePath, encoding: "utf-8" },
    ).trim();

    if (commitCount === "0") {
      console.log("[pr-creator] No commits to create PR for");
      return null;
    }

    // Push branch
    execSync(`git push -u origin ${run.branchName}`, {
      cwd: run.worktreePath,
      stdio: "pipe",
    });

    // Create PR
    const title = `[Agent-Ops] ${run.agent}/${run.jobId}: ${summary?.slice(0, 60) ?? "Automated changes"}`;
    const body = [
      "## Agent-Ops Automated PR",
      "",
      `- **Job**: ${run.jobId}`,
      `- **Run**: ${run.runId}`,
      `- **Agent**: ${run.agent}`,
      `- **Commits**: ${commitCount}`,
      "",
      summary ? `## Summary\n${summary}` : "",
      "",
      "---",
      "Generated by @yattalo/task-system Agent-Ops",
    ].join("\n");

    const prUrl = execSync(
      `gh pr create --title "${title.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"')}" --base ${run.baseBranch}`,
      { cwd: run.worktreePath, encoding: "utf-8" },
    ).trim();

    // Extract PR number from URL
    const match = prUrl.match(/\/(\d+)$/);
    const prNumber = match ? parseInt(match[1], 10) : 0;

    return { url: prUrl, number: prNumber };
  } catch (err) {
    console.error(`[pr-creator] Failed: ${(err as Error).message}`);
    return null;
  }
}
