// ============================================================
// Task System HTTP API — generated by @yattalo/task-system
// Project: my-app
// ============================================================

import { httpRouter } from "convex/server";
import { httpAction } from "../_generated/server";
import { api } from "../_generated/api";

const DEFAULT_PROJECT_ID = "visione-sostenibile" as const;

function resolveProjectId(url: URL, bodyProjectId?: string): string {
  return bodyProjectId || url.searchParams.get("projectId") || DEFAULT_PROJECT_ID;
}

// NOTE: Import this router in your main convex/http.ts:
//   import { taskSystemRoutes } from "./taskSystem/http";
//   taskSystemRoutes.forEach((route) => http.route(route));
// Or merge manually.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders },
  });
}

function errorResponse(message: string, status = 400): Response {
  return jsonResponse({ error: message }, status);
}

const optionsHandler = httpAction(async () => {
  return new Response(null, { status: 204, headers: corsHeaders });
});

const listTasks = httpAction(async (ctx, request) => {
  const url = new URL(request.url);
  const agent = url.searchParams.get("agent") || undefined;
  const status = url.searchParams.get("status") || undefined;
  const priority = url.searchParams.get("priority") || undefined;
  const wave = url.searchParams.get("wave") ? Number(url.searchParams.get("wave")) : undefined;
  const category = url.searchParams.get("category") || undefined;
  const limit = url.searchParams.get("limit") ? Number(url.searchParams.get("limit")) : undefined;
  const projectId = resolveProjectId(url);

  const tasks = await ctx.runQuery(api.taskSystem.tasks.list, {
    projectId,
    agent: agent as any,
    status,
    priority,
    wave,
    category,
    limit,
  });
  return jsonResponse(tasks);
});

const getTask = httpAction(async (ctx, request) => {
  const url = new URL(request.url);
  const taskId = url.searchParams.get("taskId");
  if (!taskId) return errorResponse("taskId is required");
  const projectId = resolveProjectId(url);

  const task = await ctx.runQuery(api.taskSystem.tasks.get, { taskId, projectId });
  if (!task) return errorResponse("Task not found", 404);
  return jsonResponse(task);
});

const getStats = httpAction(async (ctx, request) => {
  const url = new URL(request.url);
  const projectId = resolveProjectId(url);
  const stats = await ctx.runQuery(api.taskSystem.orchestrator.getStats, { projectId });
  return jsonResponse(stats);
});

const getKanban = httpAction(async (ctx, request) => {
  const url = new URL(request.url);
  const projectId = resolveProjectId(url);
  const kanban = await ctx.runQuery(api.taskSystem.orchestrator.getKanban, { projectId });
  return jsonResponse(kanban);
});

const checkDeps = httpAction(async (ctx, request) => {
  const url = new URL(request.url);
  const taskId = url.searchParams.get("taskId");
  if (!taskId) return errorResponse("taskId is required");
  const projectId = resolveProjectId(url);

  const result = await ctx.runQuery(api.taskSystem.orchestrator.checkDependencies, { taskId, projectId });
  return jsonResponse(result);
});

const changeStatus = httpAction(async (ctx, request) => {
  try {
    const url = new URL(request.url);
    const body = await request.json();
    const { taskId, newStatus, note, agent, projectId: bodyProjectId } = body;
    const projectId = resolveProjectId(url, bodyProjectId);
    if (!taskId || !newStatus) return errorResponse("taskId and newStatus are required");

    await ctx.runMutation(api.taskSystem.orchestrator.updateStatus, {
      projectId,
      taskId,
      newStatus,
      note: note || undefined,
      agent: agent || undefined,
    });
    return jsonResponse({ success: true });
  } catch (e: any) {
    return errorResponse(e.message || "Failed to update status", 500);
  }
});

const createTask = httpAction(async (ctx, request) => {
  try {
    const url = new URL(request.url);
    const body = await request.json();
    const projectId = resolveProjectId(url, body?.projectId);
    const result = await ctx.runMutation(api.taskSystem.tasks.create, { ...body, projectId });
    return jsonResponse(result);
  } catch (e: any) {
    return errorResponse(e.message || "Failed to create task", 500);
  }
});

const updateTask = httpAction(async (ctx, request) => {
  try {
    const url = new URL(request.url);
    const body = await request.json();
    const { taskId, projectId: bodyProjectId, ...fields } = body;
    const projectId = resolveProjectId(url, bodyProjectId);
    if (!taskId) return errorResponse("taskId is required");

    await ctx.runMutation(api.taskSystem.tasks.update, { taskId, projectId, fields });
    return jsonResponse({ success: true });
  } catch (e: any) {
    return errorResponse(e.message || "Failed to update task", 500);
  }
});

// Route definitions for integration into main http.ts
export const taskSystemRoutes = [
  { path: "/api/tasks/list", method: "GET" as const, handler: listTasks },
  { path: "/api/tasks/list", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/get", method: "GET" as const, handler: getTask },
  { path: "/api/tasks/get", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/stats", method: "GET" as const, handler: getStats },
  { path: "/api/tasks/stats", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/kanban", method: "GET" as const, handler: getKanban },
  { path: "/api/tasks/kanban", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/checkDependencies", method: "GET" as const, handler: checkDeps },
  { path: "/api/tasks/checkDependencies", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/changeStatus", method: "POST" as const, handler: changeStatus },
  { path: "/api/tasks/changeStatus", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/create", method: "POST" as const, handler: createTask },
  { path: "/api/tasks/create", method: "OPTIONS" as const, handler: optionsHandler },
  { path: "/api/tasks/update", method: "POST" as const, handler: updateTask },
  { path: "/api/tasks/update", method: "OPTIONS" as const, handler: optionsHandler },
];
