// ============================================================
// Task System Schema — generated by @yattalo/task-system
// Project: my-app
// DO NOT EDIT MANUALLY — re-run 'npx @yattalo/task-system init' to update
// ============================================================

import { defineTable } from "convex/server";
import { v } from "convex/values";

export const taskSystemTables = {
  // Main task table
  agentTasks: defineTable({
    // Core Identification
    projectId: v.string(),
    taskId: v.string(),
    agent: v.union(
      v.literal("claude"),
      v.literal("gemini"),
      v.literal("codex"),
    ),

    // Content
    title: v.string(),
    description: v.optional(v.string()),
    acceptanceCriteria: v.optional(v.array(v.string())),

    // Categorization
    priority: v.union(
      v.literal("critical"),
      v.literal("high"),
      v.literal("medium"),
      v.literal("low"),
    ),
    status: v.union(
      v.literal("pending"),
      v.literal("backlog"),
      v.literal("todo"),
      v.literal("in_progress"),
      v.literal("in_review"),
      v.literal("blocked"),
      v.literal("done"),
      v.literal("failed"),
      v.literal("cancelled"),
    ),
    category: v.optional(
      v.union(
        v.literal("backend"),
        v.literal("frontend"),
        v.literal("uiux"),
        v.literal("devops"),
        v.literal("review"),
        v.literal("testing"),
        v.literal("documentation"),
      ),
    ),

    // Planning
    wave: v.number(),
    estimatedHours: v.optional(v.number()),
    actualHours: v.optional(v.number()),
    storyPoints: v.optional(v.number()),

    // Phase tracking
    phaseId: v.optional(v.union(
      v.literal("foundation"),
      v.literal("core"),
      v.literal("features"),
      v.literal("polish"),
      v.literal("deploy"),
    )),

    // Dependencies
    dependencies: v.array(v.string()),
    blocks: v.optional(v.array(v.string())),

    // Files & Deliverables
    filesExpected: v.array(v.string()),
    filesCreated: v.optional(v.array(v.string())),

    // Time Tracking
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    dueDate: v.optional(v.number()),

    // Commit tracking
    commits: v.array(
      v.object({
        hash: v.string(),
        message: v.string(),
        timestamp: v.number(),
        filesChanged: v.optional(v.array(v.string())),
        agent: v.optional(v.string()),
      }),
    ),

    // Status History
    statusHistory: v.optional(
      v.array(
        v.object({
          status: v.string(),
          timestamp: v.number(),
          note: v.optional(v.string()),
          agent: v.optional(v.string()),
        }),
      ),
    ),

    // Blockers
    blockers: v.optional(
      v.array(
        v.object({
          reason: v.string(),
          createdAt: v.number(),
          resolvedAt: v.optional(v.number()),
          resolvedBy: v.optional(v.string()),
        }),
      ),
    ),

    // Metadata
    tags: v.optional(v.array(v.string())),
    notes: v.optional(v.string()),
    scopeCreepFlags: v.optional(v.array(v.string())),

    // Review findings
    reviewFindings: v.optional(
      v.object({
        critical: v.number(),
        high: v.number(),
        medium: v.number(),
        low: v.number(),
        info: v.number(),
      }),
    ),

    // Sync tracking
    lastSyncedAt: v.optional(v.number()),
    syncVersion: v.optional(v.number()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_taskId", ["taskId"])
    .index("by_projectId", ["projectId"])
    .index("by_project_taskId", ["projectId", "taskId"])
    .index("by_project_agent", ["projectId", "agent"])
    .index("by_project_status", ["projectId", "status"])
    .index("by_project_wave", ["projectId", "wave"])
    .index("by_project_priority", ["projectId", "priority"])
    .index("by_project_dueDate", ["projectId", "dueDate"])
    .index("by_project_category", ["projectId", "category"])
    .index("by_agent", ["agent"])
    .index("by_status", ["status"])
    .index("by_wave", ["wave"])
    .index("by_priority", ["priority"])
    .index("by_dueDate", ["dueDate"])
    .index("by_category", ["category"])
    .index("by_phaseId", ["phaseId"])
    .index("by_project_phaseId", ["projectId", "phaseId"])
  ,

  // Sync Log
  taskSyncLog: defineTable({
    projectId: v.string(),
    operation: v.union(v.literal("import"), v.literal("export"), v.literal("merge")),
    source: v.string(),
    agent: v.optional(v.string()),
    tasksAffected: v.number(),
    tasksCreated: v.optional(v.number()),
    tasksUpdated: v.optional(v.number()),
    tasksDeleted: v.optional(v.number()),
    errors: v.optional(v.array(v.string())),
    metadata: v.optional(v.any()),
    timestamp: v.number(),
  })
    .index("by_projectId", ["projectId"])
    .index("by_project_timestamp", ["projectId", "timestamp"])
    .index("by_operation", ["operation"])
    .index("by_agent", ["agent"])
    .index("by_timestamp", ["timestamp"]),

  // Task Comments
  taskComments: defineTable({
    projectId: v.string(),
    taskId: v.id("agentTasks"),
    author: v.string(),
    content: v.string(),
    type: v.union(
      v.literal("comment"),
      v.literal("status_change"),
      v.literal("blocker"),
      v.literal("milestone"),
    ),
    timestamp: v.number(),
  })
    .index("by_projectId", ["projectId"])
    .index("by_task", ["taskId"])
    .index("by_timestamp", ["timestamp"]),

  // Task Time Entries
  taskTimeEntries: defineTable({
    projectId: v.string(),
    taskId: v.id("agentTasks"),
    agent: v.string(),
    startedAt: v.number(),
    endedAt: v.optional(v.number()),
    duration: v.optional(v.number()),
    description: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
  })
    .index("by_projectId", ["projectId"])
    .index("by_task", ["taskId"])
    .index("by_agent", ["agent"])
    .index("by_started", ["startedAt"]),

  // Agent-Ops Jobs
  agentOpsJobs: defineTable({
    projectId: v.string(),
    jobId: v.string(),
    name: v.string(),
    description: v.optional(v.string()),
    scheduleType: v.union(v.literal("cron"), v.literal("interval"), v.literal("one-shot"), v.literal("trigger")),
    cronExpression: v.optional(v.string()),
    intervalSeconds: v.optional(v.number()),
    timezone: v.optional(v.string()),
    triggerType: v.optional(v.string()),
    triggerFilter: v.optional(v.any()),
    agent: v.union(
      v.literal("claude"),
      v.literal("gemini"),
      v.literal("codex"),
    ),
    prompt: v.string(),
    executionMode: v.union(v.literal("isolated"), v.literal("read-only"), v.literal("dry-run")),
    createPR: v.boolean(),
    prBaseBranch: v.optional(v.string()),
    maxDurationMinutes: v.optional(v.number()),
    laneId: v.optional(v.string()),
    enabled: v.boolean(),
    lastRunAt: v.optional(v.number()),
    nextRunAt: v.optional(v.number()),
    totalRuns: v.number(),
    successfulRuns: v.number(),
    failedRuns: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_projectId", ["projectId"])
    .index("by_project_jobId", ["projectId", "jobId"])
    .index("by_jobId", ["jobId"])
    .index("by_enabled", ["enabled"])
    .index("by_agent", ["agent"])
    .index("by_scheduleType", ["scheduleType"])
    .index("by_nextRunAt", ["nextRunAt"])
    .index("by_laneId", ["laneId"]),

  // Agent-Ops Runs
  agentOpsRuns: defineTable({
    projectId: v.string(),
    runId: v.string(),
    jobId: v.string(),
    status: v.union(
      v.literal("queued"),
      v.literal("provisioning"),
      v.literal("running"),
      v.literal("completing"),
      v.literal("success"),
      v.literal("failed"),
      v.literal("timeout"),
      v.literal("cancelled"),
    ),
    agent: v.union(
      v.literal("claude"),
      v.literal("gemini"),
      v.literal("codex"),
    ),
    prompt: v.string(),
    executionMode: v.string(),
    queuedAt: v.number(),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    worktreePath: v.optional(v.string()),
    branchName: v.optional(v.string()),
    baseBranch: v.optional(v.string()),
    commitCount: v.optional(v.number()),
    filesChanged: v.optional(v.number()),
    linesAdded: v.optional(v.number()),
    linesRemoved: v.optional(v.number()),
    prUrl: v.optional(v.string()),
    prNumber: v.optional(v.number()),
    prState: v.optional(v.string()),
    logs: v.array(
      v.object({
        timestamp: v.number(),
        level: v.union(v.literal("info"), v.literal("warn"), v.literal("error"), v.literal("debug")),
        message: v.string(),
      }),
    ),
    summary: v.optional(v.string()),
    error: v.optional(v.string()),
    exitCode: v.optional(v.number()),
    triggeredBy: v.union(v.literal("schedule"), v.literal("trigger"), v.literal("manual"), v.literal("retry")),
    triggerContext: v.optional(v.any()),
  })
    .index("by_projectId", ["projectId"])
    .index("by_project_runId", ["projectId", "runId"])
    .index("by_project_jobId", ["projectId", "jobId"])
    .index("by_project_status", ["projectId", "status"])
    .index("by_runId", ["runId"])
    .index("by_jobId", ["jobId"])
    .index("by_status", ["status"])
    .index("by_agent", ["agent"])
    .index("by_queuedAt", ["queuedAt"]),

};
